Produk.create(nama_produk: 'Voucher Kurma Makkah', harga: 120000, harga_diskon: 100000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Madinah', harga: 130000, harga_diskon: 110000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Pohon', harga: 140000, harga_diskon: 102000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Batu', harga: 190000, harga_diskon: 170000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Manis', harga: 180000, harga_diskon: 160000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Hitam', harga: 170000, harga_diskon: 130000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Kuning', harga: 250000, harga_diskon: 130000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Cokelat', harga: 240000, harga_diskon: 130000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Ungu', harga: 230000, harga_diskon: 130000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)
Produk.create(nama_produk: 'Voucher Kurma Segar', harga: 210000, harga_diskon: 200000, category_id: 14, user_id: 13, berat: 500, deskripsi_lengkap: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab.\rBentuknya bulat berkeriput, dengan warna coklat tua kemerah-merahan.
Rasanya manis, legit dan lembut.\rJenis Voucher Kurma Lulu ini sudah familier bagi masyarakat Indonesia karena sering dijadikan oleh-oleh haji dan umroh.\rBentuk & warnanya yang mirip Voucher Kurma ajwa ini sering membuat orang keliru sehingga menganggap Voucher Kurma ini jenis ajwa.\rDengan kemasan family pack 250 gram, cocok juga buat oleh-oleh ketika berkunjung ke sanak family, sahabat dan relasi.", deskripsi: "Voucher Kurma Lulu adalah jenis Voucher Kurma dari Uni Emrat Arab", subcategory_id: 17, harga_grosir1: 90000, harga_grosir2: 80000, jumlah_grosir1min: 1, jumlah_grosir1max: 10, jumlah_grosir2min: 11, jumlah_grosir2max: 20, toko_id: 7)